spring:
  thymeleaf:
    mode: HTML5
    servlet:
      content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    password: 123456
    username: root
  messages:
    basename: i18n/messages

logging:
  level:
    root: info
    com.qiuzhao.blog: trace



mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: com.qiuzhao.blog.domain
  config-location: classpath:mybatis-config.xml


server:
  port: 80

comment:
  avatar: /images/avatar.png
